<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H50J06T" failures="1" tests="4" name="Change Password" time="31.419" errors="0" timestamp="2021-04-28T09:05:35 ICT">
  <testcase classname="TPOS.LOGIN.ChangePwd" name="loginsuccessful" time="8.728"/>
  <testcase classname="TPOS.LOGIN.ChangePwd" name="ChangePw" time="10.188"/>
  <testcase classname="TPOS.LOGIN.ChangePwd" name="changePwdUnsuccess" time="5.348"/>
  <testcase classname="TPOS.LOGIN.ChangePwd" name="changePwdsuccess" time="6.059">
    <failure type="java.lang.AssertionError" message="expected [https://tmt30.tpos.vn/#/app/dashboard] but found [https://tmt30.tpos.vn/#/account/login]">
      <![CDATA[java.lang.AssertionError: expected [https://tmt30.tpos.vn/#/app/dashboard] but found [https://tmt30.tpos.vn/#/account/login]
at TPOS.LOGIN.ChangePwd.changePwdsuccess(ChangePwd.java:93)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- changePwdsuccess -->
</testsuite> <!-- Change Password -->
